"""add_profile_fields_to_user

Revision ID: 469bf21c5176
Revises: 8c600251c711
Create Date: 2026-03-08 15:20:36.306863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '469bf21c5176'
down_revision: Union[str, None] = '8c600251c711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_persist')
    op.add_column('exams', sa.Column('exam_time', sa.String(length=50), nullable=False))
    op.add_column('exams', sa.Column('location', sa.String(length=255), nullable=False))
    op.add_column('exams', sa.Column('invigilator_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'exams', 'staff', ['invigilator_id'], ['id'], ondelete='SET NULL')
    op.alter_column('students', 'course',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('students', 'semester',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.add_column('users', sa.Column('education', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('dob', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('info', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'info')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'dob')
    op.drop_column('users', 'education')
    op.alter_column('students', 'semester',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('students', 'course',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'exams', type_='foreignkey')
    op.drop_column('exams', 'invigilator_id')
    op.drop_column('exams', 'location')
    op.drop_column('exams', 'exam_time')
    op.create_table('test_persist',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
